// <auto-generated />
using AppTest.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppTest.Server.Migrations
{
    [DbContext(typeof(BookContext))]
    partial class BookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppTest.Server.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Matias Aravena",
                            Description = "Describing how to survive in Germany under economic depression.",
                            Price = 29.99m,
                            Title = "Book of life"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Tomas Aravena",
                            Description = "How to find a job in a new field without having much experience.",
                            Price = 39.99m,
                            Title = "Understanding how to get employed"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Sandra Edwards",
                            Description = "How to make scientific people in the ghost and spirit realm.",
                            Price = 24.99m,
                            Title = "Magic for not believers"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
